# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3212178a619c98cd11fdafbfbb81b7399541fe5f08ecb853bcf19980747f3a6810b487675ab41247b1f9a11e97e9bd9b37a221f3fdf82045a862742377e08304

test:
  secret_key_base: be5fa7706b25c628444e14834b42dd5f145c48a8b83f8d77b8657e089aa6cc5edb902d2180bb9c6979ce874a23965bc53da82a9fc684dc9b97fcd33e9baae57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
